# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_viewcactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcactus',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
